name: "Stock Prediction Deploy Script"

# Defines when the workflow will run
on:
  # Manual trigger using GitHub Actions UI
  workflow_dispatch:
    inputs:
      # Input parameter to choose between apply or destroy actions
      action:
        description: 'Terraform Action to Perform'
        type: choice
        options:
        - Terraform_apply
        - Terraform_destroy

jobs:
  # Job for applying Terraform configurations
  terraform_apply:
    name: "Terraform_apply"
    # Condition to run this job only when 'Terraform_apply' is selected
    if: ${{ github.event.inputs.action == 'Terraform_apply' }}
    # Specifies the type of runner to use
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials for authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
      
        with:
          # Using GitHub secrets for secure credential storage
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Secret variable
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Secret variable
          aws-region: ${{ vars.AWS_REGION }}  # Reference the repository variable

      - uses: actions/setup-node@v6
        with:
          # File containing the version Spec of the version to use.  Examples: package.json, .nvmrc, .node-version, .tool-versions.
          # If node-version and node-version-file are both provided the action will use version from node-version. 
          node-version-file: 'frontend/package.json'
      - run: cd frontend && npm install && npm run build && cd ..
      
      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9 # Specifies Terraform version to use
          terraform_wrapper: false

      # Step 4: Initialize Terraform working directory
      - name: Terraform Init
        run: terraform init

      # Step 5: Preview the infrastructure changes
      - name: Terraform Plan
        run: terraform plan

      # Step 6: Apply the infrastructure changes
      - name: Terraform Apply
        run: terraform apply -auto-approve # Auto-approve flag skips manual confirmation
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }} # Key pair name
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_repo_url: "https://github.com/fxlso/StockPrediction-Team1-Fall2025.git"
          
  terraform_destroy:
    name: "Terraform_destroy"
    # Condition to run this job only when 'Terraform_destroy' is selected
    if: ${{ github.event.inputs.action == 'Terraform_destroy' }}
    # Specifies the type of runner to use
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials for authentication
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
      
        with:
          # Using GitHub secrets for secure credential storage
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Secret variable
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Secret variable
          aws-region: ${{ vars.AWS_REGION }}  # Reference the repository variable

      # Step 3: Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2
        with:
          terraform_version: 1.1.9 # Specifies Terraform version to use
          terraform_wrapper: false
          
      # Step 4: Initialize Terraform working directory
      - name: Terraform Init
        run: terraform init

      # Step 5: Preview the infrastructure changes
      - name: Terraform Plan
        run: terraform plan

      # Step 6: destroy the infrastructure changes
      - name: Terraform Destory
        run: terraform destroy -auto-approve # Auto-approve flag skips manual confirmation
        env:
          TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_key_name: ${{ secrets.AWS_KEY_NAME }} # Key pair name
          TF_VAR_db_name: ${{ secrets.DB_NAME }}
          TF_VAR_repo_url: "https://github.com/fxlso/StockPrediction-Team1-Fall2025.git"
